### ISSUE TITLE
This isn't an issue

### ISSUE THREAD

**Issue by ttmarek** [tjaartvdwalt/jekyll-org-mode-converter#1]
Hi there,
I just wanted to thank you for making this. I love it when tools are this easy to set up and work so well. A few minutes ago I had a desire (wanting to write my posts in org mode), and within a minute I was already up and running. Great work!

**Comment by tjaartvdwalt** [comment]
@ttmarek 

Thank you so much for the kind words. It is really great to get positive feedback!
